name: best_practices
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN_first_time_token}